server:
    port: 2525
    servlet:
        context:
            path: /Shopme
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        name: ecomm_shopme
        password: root
        url: jdbc:mysql://localhost:3306/ecomm_shopme
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: false
        show-sql: false
        open-in-view: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id:  263056919918-q5havljgc69uqu6q06ej7d4a3ng412k9.apps.googleusercontent.com #263056919918-0ease87oocd2k2oeqk75g6dj0ih3ja71.apps.googleusercontent.com
                        client-secret:  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 #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
                        scope:
                        - email
                        - profile
                    github:
                        client-id: 0b9e99a0992b4d675b6f
                        client-secret: 474c9107194caec9a669a9876d2d68590e2dfab1
                        scope:
                        - user:email
                        - read:user