server:
    port: 2525

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        name: ecomm_shopme
        password: root
        url: jdbc:mysql://localhost:3306/ecomm_shopme
#        url: jdbc:mysql://host.docker.internal:3306/ecomm_shopme
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: false
        show-sql: false
        open-in-view: true
    redis:
        host: 127.0.0.1
#        host: host.docker.internal
        port: 6379
    cache:
        type: redis
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id:
                        client-secret:
                        scope:
                        - email
                        - profile